.eslintrc.js
package.json
src/app.js
src/index.html
src/module/timer.js
tools/build.js
yarn.lock

CORSにより`file://`からは読み込めなくなったのでexpressを使うことにした

ES Moduleの導入

---

src/app.css
src/index.html

chatに日付と時間を追加する

---

src/app.css
src/app.js
src/index.html
src/module/generator.js
src/module/prediction.js
src/module/server2client.js

Prediction関係のこと

---

src/scripts/village/components/FormattedTime.js
src/scripts/village/components/FormattedTime.test.js

FormattedTimeのtest

---

.babelrc
package.json
src/scripts/lobby/reducers/buildVillage.js
src/scripts/lobby/reducers/waitingForPlayers.js
src/scripts/village/containers/CommandContainer.js
src/scripts/village/containers/ModalContainer.js
src/scripts/village/reducers/command.js
src/scripts/village/reducers/prediction.js
yarn.lock

```js
Object.assign(
{},
state,
{
table: Object.assign(
{},
state.table,
{
[action.playerId]: Object.assign(
{},
state.table[action.playerId],
{
[action.roleId]: Object.assign(
{},
state.table[action.playerId][action.roleId],
{
state: action.nextState
}
)
}
)
}
)
}
)
```
```js
{
... state,
table: {
... state.table,
[action.playerId]: {
... state.table[action.playerId],
[action.roleId]: {
... state.table[action.playerId][action.roleId],
state: action.nextState
}
}
}
}
```

Add babel-plugin-transform-object-rest-spread

---

src/scripts/village/components/PredictionPlayer.js
src/scripts/village/components/PredictionPlayer.test.js

PledicitonPlayerのテスト

---

src/flow-typed/global.js
src/scripts/village/components/PredictionItem.js
src/scripts/village/components/PredictionItem.test.js

flow
props.handleBoardClickはもっく
ref: https://facebook.github.io/jest/docs/en/mock-function-api.html#mockfnmocknamevalue

PredictionItemのテスト

---

src/scripts/village/actions/index.js
src/scripts/village/components/Command.js
src/scripts/village/components/HideButton.js
src/scripts/village/components/HideButton.test.js
src/scripts/village/containers/ActivityContainer.js
src/scripts/village/containers/CommandContainer.js
src/scripts/village/containers/HideButtonContainer.js
src/scripts/village/reducers/hideButton.js

Test village hide button

---

flow-typed/global.js
src/scripts/village/actions/index.js

actionsのテスト

---

src/scripts/village/components/CommandOption.test.js

CommandOptionのテスト直し

---

flow-typed/global.js
flow-typed/npm/react-redux_v5.x.x.js
flow-typed/npm/redux_v3.x.x.js
src/scripts/village/components/Modal.js
src/scripts/village/components/Modal.test.js
src/scripts/village/constants/Phase.js
src/scripts/village/constants/Role.js
src/scripts/village/constants/Version.js
src/scripts/village/containers/ModalContainer.js
src/scripts/village/reducers/index.js
src/scripts/village/reducers/modal.js

reducerの型を先に書いた方がよさそう
```js
type Props =
& StateProps
& DispatchProps
& OwnProps
```

Modalのtest

---

src/scripts/village/components/AgentIcon.js
src/scripts/village/components/Agentcon.test.js
src/scripts/village/components/ChatItem.js
src/scripts/village/components/Modal.js
src/scripts/village/components/Modal.test.js
src/scripts/village/components/Role.js
src/scripts/village/components/Role.test.js
src/scripts/village/components/RoleIcon.js
src/scripts/village/components/RoleIcon.test.js
src/scripts/village/containers/RoleContainer.js

props.agentをprops.nameに変更
コンポーネント名をRoleIconからAgentIconに変更
mineではなくagentsを利用するように変更

Refactor RoleIcon

---

flow-typed/global.js
src/scripts/village/components/Result.js
src/scripts/village/components/Result.test.js
src/scripts/village/containers/CommandContainer.js
src/scripts/village/containers/ModalContainer.js
src/scripts/village/containers/ResultContainer.js
src/scripts/village/containers/RoleContainer.js
src/scripts/village/middlewares/client2server.js
src/scripts/village/reducers/agents.js
src/scripts/village/reducers/agents.test.js
src/scripts/village/reducers/result.js
src/scripts/village/reducers/result.test.js
src/scripts/village/reducers/roles.js
src/scripts/village/reducers/roles.test.js

Agent[]から{all: Agent[], mine: Agent}に変更
それに伴い，いろいろ変更

agentsとrolesのなおし

---

flow-typed/global.js
src/scripts/village/actions/index.js
src/scripts/village/components/Result.js
src/scripts/village/components/Result.test.js
src/scripts/village/containers/ResultContainer.js
src/scripts/village/module/util.js
src/scripts/village/module/util.test.js
src/scripts/village/reducers/result.js
src/scripts/village/reducers/result.test.js

Resultまわりのりふぁくた

---

.eslintrc.js
src/scripts/village/actions/index.js
src/scripts/village/components/Timer.js
src/scripts/village/components/Timer.test.js
src/scripts/village/containers/TimerContainer.js
src/scripts/village/reducers/timer.js
src/scripts/village/reducers/timer.test.js

jestのユニットテストだとやりづらいので，別の方法にする（よてい）
https://storybook.js.org/

Refactor village timer

---

src/scripts/village/reducers/fakeServer/firstDayConversationVillager.js
src/scripts/village/reducers/fakeServer/index.js
src/scripts/village/reducers/prediction.js
src/scripts/village/reducers/prediction.test.js

updatePredictionTableのテストは実装している範囲で書いた

Fix prediction type

---

flow-typed/lobby.js
src/scripts/lobby/actions/index.js
src/scripts/lobby/reducers/fakeServer/enterLobby.js
src/scripts/lobby/reducers/fakeServer/index.js
src/scripts/lobby/reducers/history.js
src/scripts/lobby/reducers/history.test.js
src/scripts/lobby/reducers/lobbyForAudience.js
src/scripts/lobby/reducers/lobbyForAudience.test.js
src/scripts/lobby/reducers/lobbyForHumanPlayer.js
src/scripts/lobby/reducers/lobbyForHumanPlayer.test.js
src/scripts/lobby/reducers/lobbyForRobotPlayer.js
src/scripts/lobby/reducers/lobbyForRobotPlayer.test.js

以下のreducerにlobbyに入った時のサーバーからのレスポンスの処理とそのテストを書いた．
- history
- lobbyForHumanPlayer
- lobbyForAudience
- lobbyForRobotPlayer

lobbyに入った時の処理とテスト

---

flow-typed/lobby.js
src/scripts/lobby/components/WaitingForPlayers.js
src/scripts/lobby/components/WaitingForPlayers.test.js
src/scripts/lobby/containers/WaitingForPlayersContainer.js
src/scripts/lobby/reducers/fakeServer/index.js
src/scripts/lobby/reducers/fakeServer/waitingPage.js
src/scripts/lobby/reducers/waitingForPlayers.js
src/scripts/lobby/reducers/waitingForPlayers.test.js

WebSocketのメッセージを処理する部分を追加．
(payload.villageをOptional(nullable)にしたため，)WaitingForPlayersとWaitingForPlayersContainerの実装もちょっと変えた

Test waitingForPlayers

---

src/index.html
src/lobby.html

#179 
Playのテンプレートの機能を使った方がいいかも？

Preload images

---

src/scripts/village/containers/ModalContainer.js

selectedAgentが存在しない場合の処理がなかったので修正

Fix ModalContainer

---

flow-typed/village.js
src/scripts/village/components/Prediction.js
src/scripts/village/reducers/prediction.js
stories/Prediction.stories.js

Add Prediction story

---

src/scripts/village/components/Chat.js
src/scripts/village/components/Chat.test.js
src/scripts/village/components/ChatItem.js
src/scripts/village/components/ChatNum.js
src/scripts/village/containers/ChatContainer.js
src/scripts/village/reducers/chat.js
src/scripts/village/reducers/chat.test.js
stories/Chat.stories.js

https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape

refactor chat

---

stories/App.stories.js
stories/initialState/dayConversationWithLimitedChat.js
stories/initialState/dayConversationWithoutLimitedChat.js
stories/initialState/dayVote.js
stories/initialState/nightVote.js
stories/initialState/results.js

Villageのstory

---

src/scripts/lobby/components/EditableVillageItem.js
src/scripts/lobby/components/EditableVillageItem.test.js
src/scripts/lobby/reducers/buildVillage.js

イベントハンドラがおかしかったので直した
条件式がおかしかったので直した

BuildVillageの修正

---

flow-typed/lobby.js
src/scripts/lobby/components/EditableVillageItem.js
src/scripts/lobby/components/VillageItem.js
src/scripts/lobby/components/VillageItem.test.js
src/scripts/lobby/components/VillageList.test.js
src/scripts/lobby/components/WaitingForPlayers.test.js
src/styles/lobby.css

Lobby id for searching

---

src/scripts/village/containers/ResultContainer.js
src/scripts/village/containers/ResultContainer.test.js
src/scripts/village/reducers/result.js
src/scripts/village/reducers/result.test.js

Fix caption

---

src/styles/app.css

overflow: scroll -> overflow: auto

---

.eslintrc.js
src/scripts/lobby/containers/LobbyForAudienceContainer.test.js
src/scripts/lobby/containers/LobbyForHumanPlayerContainer.test.js
src/scripts/lobby/containers/LobbyForRobotPlayerContainer.test.js
src/scripts/lobby/reducers/lobbyForAudience.js
src/scripts/lobby/reducers/lobbyForHumanPlayer.js
src/scripts/lobby/reducers/lobbyForRobotPlayer.js
src/scripts/lobby/reducers/waitingForPlayers.js

Refreshの処理

---

src/scripts/lobby/components/AvatarItem.js
src/scripts/lobby/components/AvatarItem.test.js
src/scripts/lobby/components/AvatarList.js
src/scripts/lobby/components/AvatarList.test.js
src/scripts/lobby/components/WaitingForPlayers.js
src/scripts/lobby/containers/WaitingForPlayersContainer.js
src/styles/lobby.css
stories/lobby/WaitingForPlayers.stories.js

pingの結果の表示

---

src/scripts/village/containers/ChatContainer.js
src/scripts/village/containers/ChatContainer.test.js
src/styles/app.css
stories/village/Chat.stories.js

delimeterなおし

---

src/scripts/lobby/components/BuildVillage.js
src/scripts/lobby/components/BuildVillage.test.js
src/scripts/lobby/components/BuildVillageBox.js
src/scripts/lobby/components/BuildVillageBox.test.js
src/scripts/lobby/containers/BuildVillageContainer.js
src/scripts/lobby/containers/BuildVillageContainer.test.js
src/scripts/lobby/reducers/buildVillage.js
src/scripts/lobby/reducers/buildVillage.test.js

Lobby build village

---

src/scripts/village/actions/index.js
src/scripts/village/components/CommandNavigation.test.js
src/scripts/village/components/CommandPostMortem.test.js
src/scripts/village/constants/ActionTypes.js
src/scripts/village/containers/CommandPostMortemContainer.js
src/scripts/village/containers/CommandPostMortemContainer.test.js
src/scripts/village/index.js
src/scripts/village/middlewares/client2server.js
src/scripts/village/middlewares/index.js
src/scripts/village/middlewares/socket.js
src/scripts/village/middlewares/timeWatcher.js
src/scripts/village/middlewares/timeWatcher.test.js
src/scripts/village/reducers/agents.js
src/scripts/village/reducers/agents.test.js
src/scripts/village/reducers/base.js
src/scripts/village/reducers/base.test.js
src/scripts/village/reducers/chat.js
src/scripts/village/reducers/chat.test.js
src/scripts/village/reducers/commandInputBox.js
src/scripts/village/reducers/commandInputBox.test.js
src/scripts/village/reducers/commandSelection.js
src/scripts/village/reducers/prediction.js
src/scripts/village/reducers/prediction.test.js
src/scripts/village/reducers/result.js
src/scripts/village/reducers/result.test.js
src/scripts/village/reducers/roles.js
src/scripts/village/reducers/roles.test.js

Village socket

---

src/scripts/village/components/atoms/Timer.js
stories/village/Timer.stories.js

`componentWillReceiveProps`が deprecatedになったので`componentDidUpdate`を使う実装に変更

Remove deprecated method

---

src/scripts/village/components/molecules/CommandInput.js

入力毎に再レンダリングされてフォーカスが外れてしまう問題の改善

CommandInputのテキスト入力の改善

---

src/i18n/lobby/ja.js
src/scripts/lobby/components/atoms/Header.js
src/scripts/lobby/components/atoms/Header.test.js
src/scripts/lobby/components/templates/AdvancedSearch.js
src/scripts/lobby/components/templates/BuildVillage.js
src/scripts/lobby/components/templates/ConnectingToRobotPlayer.js
src/scripts/lobby/components/templates/History.js
src/scripts/lobby/components/templates/IdSearch.js
src/scripts/lobby/components/templates/LobbyForAudience.js
src/scripts/lobby/components/templates/LobbyForHumanPlayer.js
src/scripts/lobby/components/templates/LobbyForRobotPlayer.js
src/scripts/lobby/components/templates/Settings.js
src/scripts/lobby/components/templates/WaitingForPlayers.js
src/scripts/lobby/reducers/advancedSearch.js
src/scripts/lobby/reducers/advancedSearch.test.js
src/scripts/lobby/reducers/idSearch.js
src/scripts/lobby/reducers/idSearch.test.js

Lobby header i18n

---

flow-typed/village.js
src/scripts/village/components/molecules/Day.js
src/scripts/village/components/molecules/Day.test.js
src/scripts/village/constants/Phase.js
src/scripts/village/containers/CommandContainer.js
src/scripts/village/containers/CommandContainer.test.js
src/scripts/village/util/index.js
src/scripts/village/util/index.test.js
stories/village/Day.stories.js
stories/village/Timer.stories.js

Village flavor text

---

src/scripts/village/middlewares/indexedDB.js

Return to Lobbyのボタンを押したら遷移するように変更
indexeddbの変更が終わったら，ここのコミットはrevertする

Add transition

---

src/scripts/lobby/components/molecules/VillageItem.js
src/scripts/lobby/components/molecules/VillageItem.test.js
src/scripts/lobby/components/organisms/VillageList.js
src/scripts/lobby/components/templates/History.js
src/scripts/lobby/components/templates/LobbyForAudience.js
src/scripts/lobby/components/templates/LobbyForHumanPlayer.js
src/scripts/lobby/components/templates/LobbyForRobotPlayer.js
src/scripts/lobby/components/templates/Main.js
src/scripts/lobby/components/templates/WaitingForPlayers.js
src/styles/lobby.css
stories/lobby/LobbyForHumanPlayer.stories.js

Lobby village item

---

src/scripts/village/middlewares/flavorText.ts

flavor textのインターバルをjsonから決定するように修正

Fix interval

---

src/scripts/indexeddb/index.ts
src/scripts/lobby/middlewares/indexedDB.ts
src/scripts/village/middlewares/indexedDB.ts

Indexeddbの調整

---

src/scripts/village/index.tsx

Add onbeforeunload

---

src/scripts/village/actions/index.ts
src/scripts/village/constants/ActionTypes.ts
src/scripts/village/containers/ChatContainer.test.tsx
src/scripts/village/middlewares/client2server.test.ts
src/scripts/village/middlewares/client2server.ts
src/scripts/village/middlewares/index.ts
src/scripts/village/reducers/chat.test.ts
src/scripts/village/reducers/chat.ts
src/scripts/village/reducers/fakeServer/index.ts
src/scripts/village/reducers/fakeServer/star.ts
types/village/index.d.ts
types/village/package.json
yarn.lock

Village star

---

src/scripts/village/components/organisms/Prediction.tsx

Fix the style of PredictionSpec

---

package.json
src/scripts/village/components/atoms/ChatText.tsx
src/scripts/village/reducers/chat.test.ts
src/scripts/village/reducers/chat.ts
src/scripts/village/util/idGenerator.test.ts
src/scripts/village/util/idGenerator.ts
src/scripts/village/util/index.test.ts
src/scripts/village/util/index.ts
tools/setupTests.js
yarn.lock

idGeneratorをUUID使う実装に変更

---

src/scripts/village/middlewares/flavorText.test.ts
src/scripts/village/reducers/chat.ts
src/scripts/village/reducers/fakeServer/myMessageOnChat.ts
src/scripts/village/reducers/fakeServer/onymousAudienceChat.ts
src/scripts/village/reducers/fakeServer/theirMessageOnChat.ts
src/scripts/village/util/convertImageUrl.test.ts
src/scripts/village/util/convertImageUrl.ts
src/scripts/village/util/index.ts

Add convertImageUrl

---

src/scripts/lobby/actions/advancedSearch.ts
src/scripts/lobby/actions/buildVillage.ts
src/scripts/lobby/actions/idSearch.ts
src/scripts/lobby/actions/index.ts
src/scripts/lobby/actions/selectHumanAvatar.ts
src/scripts/lobby/actions/selectRobotAvatar.ts
src/scripts/lobby/actions/socket.ts
src/scripts/lobby/components/molecules/SelectHumanAvatarTableBody.tsx
src/scripts/lobby/containers/AdvancedSearchContainer.ts
src/scripts/lobby/containers/BuildVillageContainer.ts
src/scripts/lobby/containers/IdSearchContainer.ts
src/scripts/lobby/containers/SelectHumanAvatarTableBodyContainer.ts
src/scripts/lobby/containers/SelectRobotAvatarTableBodyContainer.tsx
src/scripts/lobby/reducers/selectHumanAvatar.ts
src/scripts/lobby/reducers/selectRobotAvatar.ts

Lobby action

---

.storybook-integration/webpack.config.js
.storybook/webpack.config.js
package.json
src/scripts/village/components/molecules/CommandInput.test.tsx
src/scripts/village/components/molecules/CommandInput.tsx
src/scripts/village/components/organisms/CommandGrave.test.tsx
src/scripts/village/components/organisms/CommandGrave.tsx
src/scripts/village/components/organisms/CommandInputBox.test.tsx
src/scripts/village/components/organisms/CommandInputBox.tsx
src/scripts/village/components/organisms/CommandPostMortem.test.tsx
src/scripts/village/components/organisms/CommandPostMortem.tsx
src/scripts/village/containers/CommandGraveContainer.ts
src/scripts/village/containers/CommandInputBoxContainer.ts
src/scripts/village/containers/CommandPostMortemContainer.ts
src/scripts/village/reducers/suggest.ts
stories/village/Command.stories.tsx
stories/village/CommandInput.stories.tsx
webpack.config.js
yarn.lock

awesome-typescript-loader -> ts-loader

Module update

---

src/styles/lobby/selectAvatar.css

画像のサイズをCSSで予め指定することで，表示がズレるのを防止する

ページロード時のカクつき防止
